// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateClientRequest
type CreateClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *CreateClientRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CreateClientResponse
type CreateClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigFile   string `protobuf:"bytes,1,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	QrCodeBase64 string `protobuf:"bytes,2,opt,name=qr_code_base64,json=qrCodeBase64,proto3" json:"qr_code_base64,omitempty"`
	DeepLink     string `protobuf:"bytes,3,opt,name=deep_link,json=deepLink,proto3" json:"deep_link,omitempty"`
	ClientIp     string `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *CreateClientResponse) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *CreateClientResponse) GetQrCodeBase64() string {
	if x != nil {
		return x.QrCodeBase64
	}
	return ""
}

func (x *CreateClientResponse) GetDeepLink() string {
	if x != nil {
		return x.DeepLink
	}
	return ""
}

func (x *CreateClientResponse) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// DisableClientRequest
type DisableClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DisableClientRequest) Reset() {
	*x = DisableClientRequest{}
}

func (x *DisableClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableClientRequest) ProtoMessage() {}

func (x *DisableClientRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DisableClientRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DisableClientRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DisableClientResponse
type DisableClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DisableClientResponse) Reset() {
	*x = DisableClientResponse{}
}

func (x *DisableClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableClientResponse) ProtoMessage() {}

func (x *DisableClientResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DisableClientResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DisableClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisableClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EnableClientRequest
type EnableClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *EnableClientRequest) Reset() {
	*x = EnableClientRequest{}
}

func (x *EnableClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableClientRequest) ProtoMessage() {}

func (x *EnableClientRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*EnableClientRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *EnableClientRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// EnableClientResponse
type EnableClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EnableClientResponse) Reset() {
	*x = EnableClientResponse{}
}

func (x *EnableClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableClientResponse) ProtoMessage() {}

func (x *EnableClientResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*EnableClientResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *EnableClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnableClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteClientRequest
type DeleteClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DeleteClientRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetClientRequest
type GetClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *GetClientRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetClientResponse
type GetClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientIp      string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Enabled       bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RxBytes       int64  `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       int64  `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshake int64  `protobuf:"varint,6,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
}

func (x *GetClientResponse) Reset() {
	*x = GetClientResponse{}
}

func (x *GetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientResponse) ProtoMessage() {}

func (x *GetClientResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *GetClientResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetClientResponse) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *GetClientResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetClientResponse) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *GetClientResponse) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *GetClientResponse) GetLastHandshake() int64 {
	if x != nil {
		return x.LastHandshake
	}
	return 0
}

// ListClientsRequest
type ListClientsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

// ListClientsResponse
type ListClientsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clients []*ClientInfo `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *ListClientsResponse) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

// ClientInfo
type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientIp      string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Enabled       bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastHandshake int64  `protobuf:"varint,4,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	return nil
}

func (*ClientInfo) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *ClientInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClientInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ClientInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ClientInfo) GetLastHandshake() int64 {
	if x != nil {
		return x.LastHandshake
	}
	return 0
}

// Ensure emptypb is used
var _ = emptypb.Empty{}
var _ = reflect.TypeOf
var _ = sync.Mutex{}
