// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WireGuardAgent_CreateClient_FullMethodName  = "/wgagent.WireGuardAgent/CreateClient"
	WireGuardAgent_DisableClient_FullMethodName = "/wgagent.WireGuardAgent/DisableClient"
	WireGuardAgent_EnableClient_FullMethodName  = "/wgagent.WireGuardAgent/EnableClient"
	WireGuardAgent_DeleteClient_FullMethodName  = "/wgagent.WireGuardAgent/DeleteClient"
	WireGuardAgent_GetClient_FullMethodName     = "/wgagent.WireGuardAgent/GetClient"
	WireGuardAgent_ListClients_FullMethodName   = "/wgagent.WireGuardAgent/ListClients"
)

// WireGuardAgentClient is the client API for WireGuardAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WireGuardAgent - простой API для управления VPN клиентами.
//
// Основные методы:
// - CreateClient: создать нового клиента → получить конфиг, QR, ссылку
// - DisableClient: отключить клиента (подписка закончилась)
// - EnableClient: включить обратно
// - DeleteClient: удалить полностью
// - GetClient: получить информацию о клиенте
type WireGuardAgentClient interface {
	// CreateClient - создаёт нового VPN клиента.
	// Генерирует ключи, выделяет IP, добавляет в WireGuard.
	// Возвращает всё что нужно для подключения клиента.
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	// DisableClient - отключает клиента (подписка закончилась).
	// Клиент остаётся в базе, но не может подключиться.
	DisableClient(ctx context.Context, in *DisableClientRequest, opts ...grpc.CallOption) (*DisableClientResponse, error)
	// EnableClient - включает ранее отключенного клиента.
	EnableClient(ctx context.Context, in *EnableClientRequest, opts ...grpc.CallOption) (*EnableClientResponse, error)
	// DeleteClient - полностью удаляет клиента.
	DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetClient - получить информацию о клиенте.
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error)
	// ListClients - список всех клиентов.
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
}

type wireGuardAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewWireGuardAgentClient(cc grpc.ClientConnInterface) WireGuardAgentClient {
	return &wireGuardAgentClient{cc}
}

func (c *wireGuardAgentClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) DisableClient(ctx context.Context, in *DisableClientRequest, opts ...grpc.CallOption) (*DisableClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_DisableClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) EnableClient(ctx context.Context, in *EnableClientRequest, opts ...grpc.CallOption) (*EnableClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_EnableClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WireGuardAgent_DeleteClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_GetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireGuardAgentServer is the server API for WireGuardAgent service.
// All implementations must embed UnimplementedWireGuardAgentServer
// for forward compatibility.
//
// WireGuardAgent - простой API для управления VPN клиентами.
//
// Основные методы:
// - CreateClient: создать нового клиента → получить конфиг, QR, ссылку
// - DisableClient: отключить клиента (подписка закончилась)
// - EnableClient: включить обратно
// - DeleteClient: удалить полностью
// - GetClient: получить информацию о клиенте
type WireGuardAgentServer interface {
	// CreateClient - создаёт нового VPN клиента.
	// Генерирует ключи, выделяет IP, добавляет в WireGuard.
	// Возвращает всё что нужно для подключения клиента.
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	// DisableClient - отключает клиента (подписка закончилась).
	// Клиент остаётся в базе, но не может подключиться.
	DisableClient(context.Context, *DisableClientRequest) (*DisableClientResponse, error)
	// EnableClient - включает ранее отключенного клиента.
	EnableClient(context.Context, *EnableClientRequest) (*EnableClientResponse, error)
	// DeleteClient - полностью удаляет клиента.
	DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error)
	// GetClient - получить информацию о клиенте.
	GetClient(context.Context, *GetClientRequest) (*GetClientResponse, error)
	// ListClients - список всех клиентов.
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	mustEmbedUnimplementedWireGuardAgentServer()
}

// UnimplementedWireGuardAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireGuardAgentServer struct{}

func (UnimplementedWireGuardAgentServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedWireGuardAgentServer) DisableClient(context.Context, *DisableClientRequest) (*DisableClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableClient not implemented")
}
func (UnimplementedWireGuardAgentServer) EnableClient(context.Context, *EnableClientRequest) (*EnableClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableClient not implemented")
}
func (UnimplementedWireGuardAgentServer) DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (UnimplementedWireGuardAgentServer) GetClient(context.Context, *GetClientRequest) (*GetClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedWireGuardAgentServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedWireGuardAgentServer) mustEmbedUnimplementedWireGuardAgentServer() {}
func (UnimplementedWireGuardAgentServer) testEmbeddedByValue()                        {}

// UnsafeWireGuardAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireGuardAgentServer will
// result in compilation errors.
type UnsafeWireGuardAgentServer interface {
	mustEmbedUnimplementedWireGuardAgentServer()
}

func RegisterWireGuardAgentServer(s grpc.ServiceRegistrar, srv WireGuardAgentServer) {
	// If the following call pancis, it indicates UnimplementedWireGuardAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireGuardAgent_ServiceDesc, srv)
}

func _WireGuardAgent_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_DisableClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).DisableClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_DisableClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).DisableClient(ctx, req.(*DisableClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_EnableClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).EnableClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_EnableClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).EnableClient(ctx, req.(*EnableClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_DeleteClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).DeleteClient(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WireGuardAgent_ServiceDesc is the grpc.ServiceDesc for WireGuardAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireGuardAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wgagent.WireGuardAgent",
	HandlerType: (*WireGuardAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _WireGuardAgent_CreateClient_Handler,
		},
		{
			MethodName: "DisableClient",
			Handler:    _WireGuardAgent_DisableClient_Handler,
		},
		{
			MethodName: "EnableClient",
			Handler:    _WireGuardAgent_EnableClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _WireGuardAgent_DeleteClient_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _WireGuardAgent_GetClient_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _WireGuardAgent_ListClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent.proto",
}
