// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion9

const (
	WireGuardAgent_CreateClient_FullMethodName  = "/wgagent.WireGuardAgent/CreateClient"
	WireGuardAgent_DisableClient_FullMethodName = "/wgagent.WireGuardAgent/DisableClient"
	WireGuardAgent_EnableClient_FullMethodName  = "/wgagent.WireGuardAgent/EnableClient"
	WireGuardAgent_DeleteClient_FullMethodName  = "/wgagent.WireGuardAgent/DeleteClient"
	WireGuardAgent_GetClient_FullMethodName     = "/wgagent.WireGuardAgent/GetClient"
	WireGuardAgent_ListClients_FullMethodName   = "/wgagent.WireGuardAgent/ListClients"
)

// WireGuardAgentClient is the client API for WireGuardAgent service.
type WireGuardAgentClient interface {
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	DisableClient(ctx context.Context, in *DisableClientRequest, opts ...grpc.CallOption) (*DisableClientResponse, error)
	EnableClient(ctx context.Context, in *EnableClientRequest, opts ...grpc.CallOption) (*EnableClientResponse, error)
	DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error)
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
}

type wireGuardAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewWireGuardAgentClient(cc grpc.ClientConnInterface) WireGuardAgentClient {
	return &wireGuardAgentClient{cc}
}

func (c *wireGuardAgentClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) DisableClient(ctx context.Context, in *DisableClientRequest, opts ...grpc.CallOption) (*DisableClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_DisableClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) EnableClient(ctx context.Context, in *EnableClientRequest, opts ...grpc.CallOption) (*EnableClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_EnableClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WireGuardAgent_DeleteClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_GetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardAgentClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, WireGuardAgent_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireGuardAgentServer is the server API for WireGuardAgent service.
type WireGuardAgentServer interface {
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	DisableClient(context.Context, *DisableClientRequest) (*DisableClientResponse, error)
	EnableClient(context.Context, *EnableClientRequest) (*EnableClientResponse, error)
	DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error)
	GetClient(context.Context, *GetClientRequest) (*GetClientResponse, error)
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	mustEmbedUnimplementedWireGuardAgentServer()
}

type UnimplementedWireGuardAgentServer struct{}

func (UnimplementedWireGuardAgentServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedWireGuardAgentServer) DisableClient(context.Context, *DisableClientRequest) (*DisableClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableClient not implemented")
}
func (UnimplementedWireGuardAgentServer) EnableClient(context.Context, *EnableClientRequest) (*EnableClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableClient not implemented")
}
func (UnimplementedWireGuardAgentServer) DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (UnimplementedWireGuardAgentServer) GetClient(context.Context, *GetClientRequest) (*GetClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedWireGuardAgentServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedWireGuardAgentServer) mustEmbedUnimplementedWireGuardAgentServer() {}
func (UnimplementedWireGuardAgentServer) testEmbeddedByValue()                        {}

type UnsafeWireGuardAgentServer interface {
	mustEmbedUnimplementedWireGuardAgentServer()
}

func RegisterWireGuardAgentServer(s grpc.ServiceRegistrar, srv WireGuardAgentServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireGuardAgent_ServiceDesc, srv)
}

func _WireGuardAgent_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_DisableClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).DisableClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_DisableClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).DisableClient(ctx, req.(*DisableClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_EnableClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).EnableClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_EnableClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).EnableClient(ctx, req.(*EnableClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_DeleteClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).DeleteClient(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardAgent_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardAgentServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardAgent_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardAgentServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var WireGuardAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wgagent.WireGuardAgent",
	HandlerType: (*WireGuardAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _WireGuardAgent_CreateClient_Handler,
		},
		{
			MethodName: "DisableClient",
			Handler:    _WireGuardAgent_DisableClient_Handler,
		},
		{
			MethodName: "EnableClient",
			Handler:    _WireGuardAgent_EnableClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _WireGuardAgent_DeleteClient_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _WireGuardAgent_GetClient_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _WireGuardAgent_ListClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent.proto",
}
