// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"` // "wg0"
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AllowedIp     string                 `protobuf:"bytes,3,opt,name=allowed_ip,json=allowedIp,proto3" json:"allowed_ip,omitempty"`     // "10.8.0.10/32"
	KeepaliveS    int32                  `protobuf:"varint,4,opt,name=keepalive_s,json=keepaliveS,proto3" json:"keepalive_s,omitempty"` // 25
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerRequest) Reset() {
	*x = AddPeerRequest{}
	mi := &file_api_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerRequest) ProtoMessage() {}

func (x *AddPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerRequest.ProtoReflect.Descriptor instead.
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AddPeerRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *AddPeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AddPeerRequest) GetAllowedIp() string {
	if x != nil {
		return x.AllowedIp
	}
	return ""
}

func (x *AddPeerRequest) GetKeepaliveS() int32 {
	if x != nil {
		return x.KeepaliveS
	}
	return 0
}

type AddPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenPort    int32                  `protobuf:"varint,1,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerResponse) Reset() {
	*x = AddPeerResponse{}
	mi := &file_api_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerResponse) ProtoMessage() {}

func (x *AddPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerResponse.ProtoReflect.Descriptor instead.
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AddPeerResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

type RemovePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_api_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RemovePeerRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RemovePeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_api_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ListPeersRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeys    []string               `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_api_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_api_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListPeersResponse) GetPublicKeys() []string {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

var File_api_agent_proto protoreflect.FileDescriptor

const file_api_agent_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/agent.proto\x12\awgagent\x1a\x1bgoogle/protobuf/empty.proto\"\x8d\x01\n" +
	"\x0eAddPeerRequest\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"allowed_ip\x18\x03 \x01(\tR\tallowedIp\x12\x1f\n" +
	"\vkeepalive_s\x18\x04 \x01(\x05R\n" +
	"keepaliveS\"2\n" +
	"\x0fAddPeerResponse\x12\x1f\n" +
	"\vlisten_port\x18\x01 \x01(\x05R\n" +
	"listenPort\"P\n" +
	"\x11RemovePeerRequest\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"0\n" +
	"\x10ListPeersRequest\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\"4\n" +
	"\x11ListPeersResponse\x12\x1f\n" +
	"\vpublic_keys\x18\x01 \x03(\tR\n" +
	"publicKeys2\xd4\x01\n" +
	"\x0eWireGuardAgent\x12<\n" +
	"\aAddPeer\x12\x17.wgagent.AddPeerRequest\x1a\x18.wgagent.AddPeerResponse\x12@\n" +
	"\n" +
	"RemovePeer\x12\x1a.wgagent.RemovePeerRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\tListPeers\x12\x19.wgagent.ListPeersRequest\x1a\x1a.wgagent.ListPeersResponseB)Z'github.com/our-org/wg-project/api/protob\x06proto3"

var (
	file_api_agent_proto_rawDescOnce sync.Once
	file_api_agent_proto_rawDescData []byte
)

func file_api_agent_proto_rawDescGZIP() []byte {
	file_api_agent_proto_rawDescOnce.Do(func() {
		file_api_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_proto_rawDesc), len(file_api_agent_proto_rawDesc)))
	})
	return file_api_agent_proto_rawDescData
}

var file_api_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_agent_proto_goTypes = []any{
	(*AddPeerRequest)(nil),    // 0: wgagent.AddPeerRequest
	(*AddPeerResponse)(nil),   // 1: wgagent.AddPeerResponse
	(*RemovePeerRequest)(nil), // 2: wgagent.RemovePeerRequest
	(*ListPeersRequest)(nil),  // 3: wgagent.ListPeersRequest
	(*ListPeersResponse)(nil), // 4: wgagent.ListPeersResponse
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_api_agent_proto_depIdxs = []int32{
	0, // 0: wgagent.WireGuardAgent.AddPeer:input_type -> wgagent.AddPeerRequest
	2, // 1: wgagent.WireGuardAgent.RemovePeer:input_type -> wgagent.RemovePeerRequest
	3, // 2: wgagent.WireGuardAgent.ListPeers:input_type -> wgagent.ListPeersRequest
	1, // 3: wgagent.WireGuardAgent.AddPeer:output_type -> wgagent.AddPeerResponse
	5, // 4: wgagent.WireGuardAgent.RemovePeer:output_type -> google.protobuf.Empty
	4, // 5: wgagent.WireGuardAgent.ListPeers:output_type -> wgagent.ListPeersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_agent_proto_init() }
func file_api_agent_proto_init() {
	if File_api_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_proto_rawDesc), len(file_api_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agent_proto_goTypes,
		DependencyIndexes: file_api_agent_proto_depIdxs,
		MessageInfos:      file_api_agent_proto_msgTypes,
	}.Build()
	File_api_agent_proto = out.File
	file_api_agent_proto_goTypes = nil
	file_api_agent_proto_depIdxs = nil
}
